"""
Scheduled email report service.
Uses aiosmtplib for async SMTP delivery.
"""
import logging
from datetime import datetime, timedelta
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional

from app.core.config import settings

logger = logging.getLogger(__name__)


class EmailReportService:
    """Sends PDF reports via SMTP."""

    @staticmethod
    async def send_report(
        to_emails: List[str],
        subject: str,
        body_html: str,
        pdf_attachment: Optional[bytes] = None,
        filename: str = "report.pdf",
    ) -> bool:
        """Send an email with an optional PDF attachment."""
        if not settings.SMTP_HOST:
            logger.warning("SMTP not configured — email skipped.")
            return False

        try:
            import aiosmtplib

            msg = MIMEMultipart("mixed")
            msg["Subject"] = subject
            msg["From"] = f"{settings.FROM_NAME} <{settings.FROM_EMAIL}>"
            msg["To"] = ", ".join(to_emails)

            msg.attach(MIMEText(body_html, "html", "utf-8"))

            if pdf_attachment:
                part = MIMEApplication(pdf_attachment, _subtype="pdf")
                part.add_header(
                    "Content-Disposition", "attachment", filename=filename
                )
                msg.attach(part)

            await aiosmtplib.send(
                msg,
                hostname=settings.SMTP_HOST,
                port=settings.SMTP_PORT,
                username=settings.SMTP_USER or None,
                password=settings.SMTP_PASSWORD or None,
                use_tls=settings.SMTP_TLS,
                start_tls=settings.SMTP_STARTTLS,
            )
            logger.info(f"Report email sent to {to_emails}")
            return True
        except Exception as e:
            logger.error(f"Failed to send report email: {e}")
            return False

    @staticmethod
    def build_report_email_body(
        org_name: str,
        period_start: str,
        period_end: str,
        total_commits: int,
        active_devs: int,
        merge_rate: float,
        avg_cycle_time: float,
    ) -> str:
        """Build a simple HTML email body for the weekly report."""
        return f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: Arial, sans-serif; color: #1a1a2e; background: #f9fafb; margin:0; padding:0; }}
    .container {{ max-width: 600px; margin: 32px auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,.08); }}
    .hero {{ background: linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%); color: white; padding: 32px 36px; }}
    .hero h1 {{ font-size: 22px; margin-bottom: 6px; }}
    .hero p {{ opacity: .8; font-size: 13px; }}
    .content {{ padding: 28px 36px; }}
    .kpi-grid {{ display: grid; grid-template-columns: repeat(2,1fr); gap: 14px; margin: 20px 0; }}
    .kpi {{ background:#f0f7ff; border:1px solid #bfdbfe; border-radius:8px; padding:14px 16px; }}
    .kpi-val {{ font-size:24px; font-weight:800; color:#2563eb; }}
    .kpi-lbl {{ font-size:11px; color:#6b7280; margin-top:2px; }}
    .btn {{ display:inline-block; background:#2563eb; color:white; text-decoration:none; padding:12px 28px; border-radius:8px; font-weight:600; font-size:13px; margin-top:20px; }}
    .footer {{ padding:18px 36px; border-top:1px solid #e5e7eb; font-size:11px; color:#9ca3af; }}
  </style>
</head>
<body>
<div class="container">
  <div class="hero">
    <h1>Weekly Report — {org_name}</h1>
    <p>{period_start} &rarr; {period_end}</p>
  </div>
  <div class="content">
    <p style="color:#4b5563;font-size:13px;">Here&rsquo;s your team&rsquo;s performance summary for the past week. Full details are in the attached PDF.</p>
    <div class="kpi-grid">
      <div class="kpi">
        <div class="kpi-val">{total_commits:,}</div>
        <div class="kpi-lbl">Commits</div>
      </div>
      <div class="kpi">
        <div class="kpi-val">{active_devs}</div>
        <div class="kpi-lbl">Active Developers</div>
      </div>
      <div class="kpi">
        <div class="kpi-val">{merge_rate}%</div>
        <div class="kpi-lbl">PR Merge Rate</div>
      </div>
      <div class="kpi">
        <div class="kpi-val">{avg_cycle_time}h</div>
        <div class="kpi-lbl">Avg Cycle Time</div>
      </div>
    </div>
    <p style="font-size:12px;color:#6b7280;">The full report with charts and contributor breakdown is attached as a PDF.</p>
  </div>
  <div class="footer">
    This report was automatically generated by DevMetrics &bull; <a href="#" style="color:#2563eb;">Unsubscribe</a>
  </div>
</div>
</body>
</html>
"""
