'use client';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

const insights = [
  {
    title: 'High PR Cycle Time Detected',
    description:
      'Average PR cycle time has increased by 35% over the last two weeks. Consider reducing PR size or improving review processes.',
    severity: 'warning',
    category: 'Productivity',
    date: '2 hours ago',
  },
  {
    title: 'Code Review Bottleneck',
    description:
      'Bob Smith has 8 pending code reviews older than 24 hours. Reassigning reviews could improve team velocity.',
    severity: 'high',
    category: 'Team',
    date: '5 hours ago',
  },
  {
    title: 'Positive Trend: Test Coverage',
    description:
      'Test coverage has improved from 72% to 81% this month. Great job maintaining code quality!',
    severity: 'success',
    category: 'Quality',
    date: '1 day ago',
  },
  {
    title: 'Weekend Work Pattern',
    description:
      'Three team members have been consistently working on weekends. Consider workload balancing to prevent burnout.',
    severity: 'warning',
    category: 'Wellbeing',
    date: '2 days ago',
  },
];

const severityColors: Record<string, string> = {
  high: 'destructive',
  warning: 'warning',
  success: 'success',
  info: 'secondary',
};

export default function InsightsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">AI Insights</h1>
        <p className="text-gray-600 mt-2">
          AI-powered recommendations to improve your team&apos;s productivity
        </p>
      </div>

      {/* Insights Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold">{insights.length}</div>
            <p className="text-sm text-gray-500">Active Insights</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold text-orange-600">2</div>
            <p className="text-sm text-gray-500">Needs Attention</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold text-green-600">1</div>
            <p className="text-sm text-gray-500">Positive Trends</p>
          </CardContent>
        </Card>
      </div>

      {/* Insights List */}
      <div className="space-y-4">
        {insights.map((insight, i) => (
          <Card key={i}>
            <CardHeader>
              <div className="flex items-start justify-between">
                <div className="space-y-1">
                  <CardTitle className="text-lg">{insight.title}</CardTitle>
                  <CardDescription>{insight.date}</CardDescription>
                </div>
                <div className="flex items-center space-x-2">
                  <Badge variant={severityColors[insight.severity] as 'default'}>
                    {insight.severity}
                  </Badge>
                  <Badge variant="outline">{insight.category}</Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">{insight.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* AI Info */}
      <Card>
        <CardHeader>
          <CardTitle>About AI Insights</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-gray-600 text-sm">
            Insights are generated by analyzing your team&apos;s development
            patterns using GPT-4. They are refreshed daily and take into account
            commit frequency, PR cycle times, code review patterns, and team
            workload distribution. Connect your repositories in Settings to
            enable real-time insights.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
